### ISSUE TITLE
勇哥你好

### ISSUE THREAD

**Issue by EvanMeek** [manateelazycat/manateelazycat#1]
一年前无意发现deepin(我使用的第一个Linux发行版)，在deepin论坛中无意了解勇哥，前几天在Emacs China论坛发现勇哥居然也在...我还以为勇哥常年在国外论坛...

本向上github上搜索一下i3wm的相关指南，结果正好看到勇哥创建了个库，居然是博客!哈哈这一切真有趣，因为我昨天也搞了博客。

**Comment by manateelazycat** [comment]
哈哈哈, 很高兴见到你, issue 完美解决. ;)
